import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:estore/features/authentication/models/user_model.dart';
import 'package:estore/utils/exceptions/firebase_exceptions.dart';
import 'package:estore/utils/exceptions/format_exceptions.dart';
import 'package:estore/utils/exceptions/platform_exceptions.dart';
import 'package:get/get.dart';

class UserRepository extends GetxController {
  static UserRepository get instance => Get.find();

  final FirebaseFirestore _db = FirebaseFirestore.instance;

  Future<void> saveUserRecord(UserModel user) async {
    try {
      await _db.collection("Users").doc(user.id).set(user.toJson());
    } on TFirebaseException catch (e) {
      throw TFirebaseException(e.code).message;
    } on TFormatException catch (_) {
      throw const TFormatException();
    } on TPlatformException catch (e) {
      throw TPlatformException(e.code).message;
    } catch (e) {
      throw 'Something went wrong.Please try again';
    } finally {}
  }
}
